version: '3.8'

services:
  app:
    build: .
    container_name: ja_gabaritei_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ja_gabaritei_development
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:13
    container_name: ja_gabaritei_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ja_gabaritei_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: ja_gabaritei_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
